// +build !ignore_autogenerated

// Code generated by deepcopy-gen. DO NOT EDIT.

package config

import (
	golibqdconfig "sylr.dev/libqd/config"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MyAppConfiguration) DeepCopyInto(out *MyAppConfiguration) {
	*out = *in
	if in.Verbose != nil {
		in, out := &in.Verbose, &out.Verbose
		*out = make([]bool, len(*in))
		copy(*out, *in)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MyAppConfiguration.
func (in *MyAppConfiguration) DeepCopy() *MyAppConfiguration {
	if in == nil {
		return nil
	}
	out := new(MyAppConfiguration)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyConfig is an autogenerated deepcopy function, copying the receiver, creating a new golibqdconfig.Config.
func (in *MyAppConfiguration) DeepCopyConfig() golibqdconfig.Config {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}
