name: Go
on: [push, pull_request]
jobs:
  build:
    name: Build
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
      matrix:
        go: ["1.15", "1.16", "1.17"]
    steps:
    - name: Set up Go ${{ matrix.go }}
      uses: actions/setup-go@v1
      with:
        go-version: ${{ matrix.go }}
      id: go
    - name: Check out code into the Go module directory
      uses: actions/checkout@v1
    - name: Verify go mod
      run: make go-mod-verify
      if: matrix.go == '1.17'
    - name: Lint
      run: make lint
    - name: Test
      run: |
        export TMPDIR=$(pwd)/tmp
        mkdir -p $TMPDIR
        make test CODECOV=1 VERBOSE=1
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v1
      with:
        files: coverage.txt
      if: matrix.go == '1.16'
