name: Semgrep
on: [pull_request]
jobs:
  semgrep:
    runs-on: ubuntu-20.04
    name: Check
    steps:
    - uses: actions/checkout@v1
    - name: Semgrep
      id: semgrep
      uses: returntocorp/semgrep-action@v1
      with:
        config: r/all
